user-repo-redis: implement user-repo with redis cache
IntoMicroservices/FacebookClone pull request #11
Opened 2021-08-10 11:36 UTC by Wawrzyniec-Nowak

2021-08-11 11:03 UTC, psieniawski requested changes
Trzeba dodać konfigurację (autokonfiguracja springowa) pod ten moduł w module user-service-spring-boot-starter. W miarę możliwości powinna się wykluczać z konfiguracją inmem. W tym momencie będą dwa moduły user-repo: inmem i redis. Trzeba zmodyfikować dependency w pomie user-spring-boot-app tak, by podłączany był albo moduł inmem, albo redis. Pewnie w tym momencie najlepiej za pomocą profili mavena. Tworzenie i konfiguracja klienta redisa w user-service-spring-boot-starter. Dane do konfiguracji w application.properties. Mogą być domyślne w resource'ach user-service-spring-boot-starter. Na pewno powinna być możliwość konfigurowania/nadpisywania domyślnych w propsach user-...-app. Trzeba przygotować automat do uruchamiania Redisa - w tym momencie zapewne wystarczy jakaś prosta konfiguracja dockerowa w osobnym podfolderze naszego roota - byłby to zaczątek konfiguracji dockerowych pod kolejne serwisy.

Generalnie chodzi o to by móc zbudować sobie user-...-app na inmem, bądź redisie podając opcję jaka nas interesuje i postawić redisa też najprościej jak się da: teraz pewnie ręcznie odpalany docker.

2021-08-12 08:57 UTC, Wawrzyniec-Nowak commented on user-service-spring-boot-starter/pom.xml
> +            <version>${project.version}</version>
nigdy nie bylem dobry w build toolach wiec nie rozumiem czemu tutaj wymaga ode mnie podania version a dla user-repo-inmem juz nie

2021-08-12 08:58 UTC, Wawrzyniec-Nowak commented on user-service-spring-boot-starter/pom.xml
> +            <groupId>org.redisson</groupId>
podobnie nie rozumiem czemu potrzebuje tutaj tej biblioteki explicite a nie wpada ona z user-repo-redis

2021-08-12 11:27 UTC, psieniawski commented on user-service-spring-boot-starter/pom.xml
> +            <version>${project.version}</version>
Prawdopodobnie nie masz user-repo-redis w dependencyManagement w głównym pom.xml

2021-08-12 13:43 UTC, Wawrzyniec-Nowak commented on user-service-spring-boot-starter/pom.xml
> +            <version>${project.version}</version>
Faktycznie, dzięki!

2021-08-12 13:43 UTC, Wawrzyniec-Nowak commented on user-service-spring-boot-starter/pom.xml
> +            <groupId>org.redisson</groupId>
Podobnie jak wyżej. Problem rozwiązany poprzez dodanie redis-repo do dependency managementu.

2021-08-12 19:51 UTC, psieniawski commented on user-service-spring-boot-starter/pom.xml
> +        <sonar.coverage.exclusions>**/UserRepoInmemConfiguration.java,**/UserServiceAutoConfiguration.java,**/UserRepoRedisConfiguration.java</sonar.coverage.exclusions>
OK, to w takim razie innym razem.

2021-08-12 19:52 UTC, psieniawski commented on user-service-spring-boot-starter/pom.xml
> +        <sonar.coverage.exclusions>**/UserRepoInmemConfiguration.java,**/UserServiceAutoConfiguration.java,**/UserRepoRedisConfiguration.java</sonar.coverage.exclusions>
OK, to w takim razie innym razem.

2021-08-12 19:53 UTC, psieniawski commented on user-service-spring-boot-starter/src/main/java/klon/user/service/autoconfigure/UserRepoRedisConfiguration.java
> +        config.useSingleServer()
OK

2021-08-12 19:54 UTC, psieniawski commented on user-service-spring-boot-starter/src/main/java/klon/user/service/autoconfigure/UserRepoRedisConfiguration.java
> +        config.useSingleServer()
OK

2021-08-12 19:57 UTC, psieniawski requested changes
Poza zmianami profili mvn, jest ok.

2021-08-12 19:57 UTC, psieniawski commented on user-spring-boot-app/pom.xml
> +            <id>inmem-repo</id>
Bardziej user-inmem. inmem-repo może równie dobrze pasować do message-service, które gdzieś tu zaraz ma powstać.

2021-08-12 19:57 UTC, psieniawski commented on user-spring-boot-app/pom.xml
> +            <id>redis-repo</id>
Jak dla inmem.

2021-08-13 16:02 UTC, psieniawski approved these changes

2021-08-14 11:36 UTC, luk-perski approved these changes

2021-08-16 05:24 UTC, merged